# Generated by Django 4.2.4 on 2024-01-05 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0001_initial"),
        ("co_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Authentication.teacher_authentication",
                to_field="user_ID",
            ),
        ),
    ]
