# Generated by Django 4.2.4 on 2024-01-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0001_initial"),
        ("co_admin", "0002_alter_subject_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(default="None", max_length=20)),
                ("section", models.CharField(default="None", max_length=20)),
                (
                    "co_admin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.admin_authentication",
                    ),
                ),
            ],
        ),
    ]
