# Generated by Django 4.2.4 on 2024-01-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("co_admin", "0003_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="code_to_access",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
