# Generated by Django 4.2.4 on 2024-01-07 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("co_admin", "0004_semester_code_to_access"),
    ]

    operations = [
        migrations.RenameField(
            model_name="semester",
            old_name="code_to_access",
            new_name="access_code",
        ),
    ]
