# Generated by Django 4.2.4 on 2024-01-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("co_admin", "0007_subject_semester_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="access_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
