# Generated by Django 4.2.4 on 2024-01-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0002_delete_student_authentication"),
        ("co_admin", "0008_alter_semester_access_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="attendanceDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField(null=True)),
                (
                    "co_admin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.admin_authentication",
                    ),
                ),
            ],
        ),
    ]
