# Generated by Django 4.2.1 on 2024-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("co_admin", "0011_attendancedate_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancedate",
            name="hour",
            field=models.IntegerField(default=0),
        ),
    ]
