# Generated by Django 4.2.1 on 2024-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("co_admin", "0012_attendancedate_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedate",
            name="hour",
            field=models.IntegerField(default=1),
        ),
    ]
