# Generated by Django 4.2.4 on 2024-03-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("co_admin", "0011_attendancedate_subject_code"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="attendance_date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allotted_date", models.DateField()),
                (
                    "subject_ForeignKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="co_admin.subject",
                    ),
                ),
            ],
        ),
    ]
