# Generated by Django 4.2.4 on 2024-03-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_alter_student_authentication_parant_phone_and_more"),
        ("teacher", "0003_attendance_date_additional_hover"),
    ]

    operations = [
        migrations.CreateModel(
            name="attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_boolean", models.BooleanField(default=False)),
                (
                    "attendance_date_ForeignKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.attendance_date",
                    ),
                ),
                (
                    "student_ForeignKry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student_authentication",
                        to_field="user_ID",
                    ),
                ),
            ],
        ),
    ]
