# Generated by Django 4.2.1 on 2024-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0006_alter_attendance_date_additional_hover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_date",
            name="additional_hover",
            field=models.IntegerField(default=1),
        ),
    ]
