# Generated by Django 4.2.4 on 2024-01-04 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin_authentication",
            name="course",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
