# Generated by Django 4.2.4 on 2024-01-07 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="student_Authentication",
        ),
    ]
