# Generated by Django 4.2.4 on 2024-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0003_alter_admin_authentication_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_authentication",
            name="course",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
