# Generated by Django 4.2.4 on 2024-01-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0004_alter_admin_authentication_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_authentication",
            name="Name",
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name="admin_authentication",
            name="password",
            field=models.CharField(max_length=1001),
        ),
        migrations.AlterField(
            model_name="admin_authentication",
            name="user_ID",
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
