# Generated by Django 4.2.4 on 2024-01-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Authentication", "0002_delete_student_authentication"),
        ("co_admin", "0007_subject_semester_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="student_Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("phone", models.CharField(default=None, max_length=25)),
                ("email", models.EmailField(default=None, max_length=254)),
                ("user_ID", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=1000)),
                (
                    "co_admin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.admin_authentication",
                    ),
                ),
                (
                    "sem",
                    models.ForeignKey(
                        default="2A",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="co_admin.semester",
                        to_field="access_code",
                    ),
                ),
            ],
        ),
    ]
